In [2]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Sumathi\Downloads\Luxury_Housing_Bangalore.csv")
df.head()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.

In [3]:
df.shape

(101000, 18)

In [4]:
print("------------Data Types----------------")
print(df.dtypes)

------------Data Types----------------
Property_ID                 str
Micro_Market                str
Project_Name                str
Developer_Name              str
Unit_Size_Sqft          float64
Configuration               str
Ticket_Price_Cr             str
Transaction_Type            str
Buyer_Type                  str
Purchase_Quarter            str
Connectivity_Score      float64
Amenity_Score           float64
Possession_Status           str
Sales_Channel               str
NRI_Buyer                   str
Locality_Infra_Score    float64
Avg_Traffic_Time_Min      int64
Buyer_Comments              str
dtype: object

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  str
 1   Micro_Market          101000 non-null  str
 2   Project_Name          101000 non-null  str
 3   Developer_Name        101000 non-null  str
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Configuration         101000 non-null  str
 6   Ticket_Price_Cr       90981 non-null   str
 7   Transaction_Type      101000 non-null  str
 8   Buyer_Type            101000 non-null  str
 9   Purchase_Quarter      101000 non-null  str
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  str
 13  Sales_Channel         101000 non-null  str
 14  NRI_Buyer             101000 non-null  str
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   str
dtypes: float64(4), int64(1), str(13)
memory usage: 13.9 MB

In [6]:
df.describe()

,Unit_Size_Sqft,Connectivity_Score,Amenity_Score,Locality_Infra_Score,Avg_Traffic_Time_Min
count,90954.000000,101000.000000,90910.000000,101000.000000,101000.000000
mean,5972.274765,6.992619,7.503663,7.498426,67.182921
std,1783.397836,1.731757,1.440758,1.443128,30.271611
min,-1.000000,4.000031,5.000224,5.000013,15.000000
25%,4477.250000,5.494526,6.260329,6.247954,41.000000
50%,5990.000000,6.985805,7.499123,7.495614,67.000000
75%,7497.000000,8.490000,8.752207,8.749824,93.000000
max,8999.000000,9.999970,9.999865,9.999956,119.000000

In [7]:
df.describe(include='object')

C:\Users\Sumathi\AppData\Local\Temp\ipykernel_2800\87514550.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

,Property_ID,Micro_Market,Project_Name,Developer_Name,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Possession_Status,Sales_Channel,NRI_Buyer,Buyer_Comments
count,101000,101000,101000,101000,101000,90981,101000,101000,101000,101000,101000,101000,82713
unique,100000,48,500,11,9,72854,2,5,8,3,4,2,9
top,PROP000051,Jayanagar,Project_7,Prestige,5Bhk+,100.0,Secondary,CXO,2024-03-31,Under construction,Online,no,Great value for money.
freq,2,2176,207,9318,11375,278,50506,20340,12750,33769,25411,50516,9383

In [8]:
#check the duplicate rows
duplicate_count=df.duplicated().sum()
print(f"Total duplicated rows:{duplicate_count}")

Total duplicated rows:1000

In [9]:
#check the null value
null_count=df.isna().sum()
print(f"Total null count:{null_count}")

Total null count:Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft          10046
Configuration               0
Ticket_Price_Cr         10019
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10090
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

In [10]:
#check the null value
null_count=df.isna().sum()
print(f"Total null count:{null_count}")

Total null count:Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft          10046
Configuration               0
Ticket_Price_Cr         10019
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10090
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

In [11]:
#null percentage
null_percentage=df.isna().sum() /len(df)*100 
print(f"null_percentage:{null_percentage}")

null_percentage:Property_ID              0.000000
Micro_Market             0.000000
Project_Name             0.000000
Developer_Name           0.000000
Unit_Size_Sqft           9.946535
Configuration            0.000000
Ticket_Price_Cr          9.919802
Transaction_Type         0.000000
Buyer_Type               0.000000
Purchase_Quarter         0.000000
Connectivity_Score       0.000000
Amenity_Score            9.990099
Possession_Status        0.000000
Sales_Channel            0.000000
NRI_Buyer                0.000000
Locality_Infra_Score     0.000000
Avg_Traffic_Time_Min     0.000000
Buyer_Comments          18.105941
dtype: float64

In [12]:
df=df.drop_duplicates()
print(f"remaining rows after removed duplicates: {len(df)}")

remaining rows after removed duplicates: 100000

                                 1. filling null values in'Ticket_Price_Cr' column

In [13]:
#convert the str into numeric:
#errors='coerce' to handle the error if number in text

df['Ticket_Price_Cr'] =pd.to_numeric(df["Ticket_Price_Cr"],errors='coerce')

#to check the changes:
price_status=df['Ticket_Price_Cr'].describe()
print(price_status)

count    72049.000000
mean        12.722005
std          7.675012
min         -0.519437
25%         10.008550
50%         12.035264
75%         14.098380
max        100.000000
Name: Ticket_Price_Cr, dtype: float64

In [14]:
df['Ticket_Price_Cr'].isnull().sum()

np.int64(27951)

In [15]:
import numpy as np
#1. replace negative values and 0 with NaN  
df.loc[df['Ticket_Price_Cr'] <=0, 'Ticket_Price_Cr'] =np.nan

#2. replace the null value with the median
price_median = df['Ticket_Price_Cr'].median()
df['Ticket_Price_Cr'] = df['Ticket_Price_Cr'].fillna(price_median)
df['Ticket_Price_Cr'].describe()

count    100000.000000
mean         12.530602
std           6.521440
min           0.776524
25%          10.845884
50%          12.035451
75%          13.232463
max         100.000000
Name: Ticket_Price_Cr, dtype: float64

In [16]:
df['Ticket_Price_Cr'].isnull().sum()

np.int64(0)

                                  2.filling null values in 'Unit_Size_Sqft' column

In [17]:
#1. Turn negative/zero into NaN
df.loc[df['Unit_Size_Sqft'] <=0, 'Unit_Size_Sqft'] = np.nan
df['Unit_Size_Sqft'].describe()

count    89543.000000
mean      6005.393085
std       1731.276595
min       3000.000000
25%       4504.000000
50%       6004.000000
75%       7505.000000
max       8999.000000
Name: Unit_Size_Sqft, dtype: float64

In [18]:
#fill the null value with the median value
size_median=df['Unit_Size_Sqft'].median()
df['Unit_Size_Sqft']=df['Unit_Size_Sqft'].fillna(size_median)
df['Unit_Size_Sqft'].describe()

count    100000.000000
mean       6005.247410
std        1638.257026
min        3000.000000
25%        4683.000000
50%        6004.000000
75%        7332.000000
max        8999.000000
Name: Unit_Size_Sqft, dtype: float64

In [19]:
df['Unit_Size_Sqft'].isnull().sum()

np.int64(0)

                                       3.filling null values in 'Amenity_Score' column

In [20]:
df['Amenity_Score'].describe()

count    90000.000000
mean         7.504185
std          1.440567
min          5.000224
25%          6.261394
50%          7.499766
75%          8.752300
max          9.999865
Name: Amenity_Score, dtype: float64

In [21]:
df['Amenity_Score'].isnull().sum()

np.int64(10000)

In [22]:
# filling the null values in 'Amenity_Score' column with mean:
df['Amenity_Score'] = df['Amenity_Score'].fillna(df['Amenity_Score'].mean())
df['Amenity_Score'].isnull().sum()

np.int64(0)

In [23]:
df['Configuration'].isnull().sum()

np.int64(0)

In [24]:
df.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft              0
Configuration               0
Ticket_Price_Cr             0
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score               0
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18099
dtype: int64

In [25]:
# filling the null values in 'Buyer_Comments ' column:
df['Buyer_Comments'] = df['Buyer_Comments'].fillna("No Comment Provided")
df['Buyer_Comments'].isnull().sum()

np.int64(0)

In [26]:
# 'Configuration' column,'Micro_Market' column:
df['Configuration'] = df['Configuration'].str.upper().str.strip()
df['Micro_Market'] = df['Micro_Market'].str.title().str.strip()

In [ ]:
# 1. Clean the column names (Lowercase and strip spaces)
df.columns = df.columns.str.strip().str.lower()

# 2. Re-calculate using the NEW lowercase names
# (ticket_price_cr and unit_size_sqft)
df["price_per_sqft"] = (df["ticket_price_cr"] * 10000000) / df["unit_size_sqft"]

# 3. Handle the Date (purchase_quarter)
df['temp_date'] = pd.to_datetime(df['purchase_quarter'])
df['purchase_year'] = df['temp_date'].dt.year
df['quarter_number'] = df['temp_date'].dt.quarter

# 4. Create the Booking Flag
df['booking_flag'] = df['possession_status'].notna().astype(int)

# 5. Clean up and view
df.drop(columns=['temp_date'], inplace=True)
print(df[['purchase_quarter', 'price_per_sqft', 'purchase_year','booking_flag']].head())

  purchase_quarter  price_per_sqft  purchase_year  booking_flag
0       2023-12-31    14579.354377           2023             1
1       2023-06-30    21067.333828           2023             1
2       2023-09-30    18364.191448           2023             1
3       2023-09-30    33453.223392           2023             1
4       2025-03-31    14645.748810           2025             1

In [32]:
import pandas as pd
from sqlalchemy import create_engine


db_url = "postgresql://mydb_w3u1_user:5AQ2gYDdRgB9G4503GUL7k2WuyxfWZfT@dpg-d6e0it4tgctc73cim3v0-a.singapore-postgres.render.com:5432/mydb_w3u1"

# 2. Create the engine
engine = create_engine(db_url)

# 3. Read the table
df = pd.read_sql_table("luxury_sales_cleaned", engine)

print(f"Success! Loaded {len(df)} rows.")

Success! Loaded 100000 rows.